"""remove username

Revision ID: 00d35df39ee8
Revises: e952a3a6faf5
Create Date: 2022-10-18 23:42:23.187106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00d35df39ee8'
down_revision = 'e952a3a6faf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dosen', ['email'])
    op.create_unique_constraint(None, 'mahasiswa', ['email'])
    op.drop_index('username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('username', 'user', ['username'], unique=False)
    op.drop_constraint(None, 'mahasiswa', type_='unique')
    op.drop_constraint(None, 'dosen', type_='unique')
    # ### end Alembic commands ###
