"""student rem

Revision ID: 8700328aec24
Revises: f76f4a23e221
Create Date: 2022-10-20 13:02:15.291511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8700328aec24'
down_revision = 'f76f4a23e221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_class_ibfk_1', 'student_class', type_='foreignkey')
    op.drop_column('student_class', 'npm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_class', sa.Column('npm', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('student_class_ibfk_1', 'student_class', 'student', ['npm'], ['npm'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
