"""remove phone

Revision ID: e952a3a6faf5
Revises: 541e349e0ed1
Create Date: 2022-10-18 23:26:58.944467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e952a3a6faf5'
down_revision = '541e349e0ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dosen', 'phone')
    op.drop_column('mahasiswa', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('dosen', sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
